# -*- coding: utf-8 -*-
"""Exp1_stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185hg2SBunDTTjfRCvcj0xaEdPOMNzb2x
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
df = pd.read_csv("diabetes.csv")

# Display first five records
print("First Five Records")
print(df.head())

# Dataset Information
print("\nDataset Information")
print(df.info())

# Dataset Shape
print("\nDataset Shape:")
print(df.shape)

# Column Names
print("\nColumn Names")
print(df.columns)

# Data Types
print("\nData Types")
print(df.dtypes)

# Statistical Summary
print("\nStatistical Summary")
print(df.describe())

# Missing Values
print("\nMissing Values")
print(df.isnull().sum())

# Check invalid zero values
columns = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

print("\nInvalid Zero Values")

for col in columns:
    print(col, (df[col] == 0).sum())

# Boxplots
plt.figure(figsize=(15,8))

for i, col in enumerate(columns):
    plt.subplot(2,3,i+1)
    sns.boxplot(y=df[col])
    plt.title(col)

plt.tight_layout()
plt.show()

# Histograms
df.hist(figsize=(12,10))
plt.show()

# Diabetes Outcome Count
plt.figure(figsize=(5,4))
sns.countplot(x='Outcome', data=df)
plt.title("Outcome Distribution")
plt.show()

# Scatter Plot
plt.figure(figsize=(6,5))
sns.scatterplot(x='Glucose', y='BMI', hue='Outcome', data=df)
plt.title("Glucose vs BMI")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

from google.colab import files

uploded = files.upload()

